---
title: "Lab 5 Individual work"
author: "Andrew Maloney"
date: "4/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(maps)
library(plotly)
library(gridExtra)
```




```{r}

accident <-  read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/accident.csv", stringsAsFactors = FALSE)

person <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/person.csv", stringsAsFactors = FALSE)

```


```{r}
names(accident)
names(person)

```


```{r}
#summary(Accident$DAY_WEEK)
#summary(Accident$HOUR)
#Changing labels was not thought up by our team.  We stumbled across this idea @ http://www.sthda.com/english/wiki/ggplot2-axis-ticks-a-guide-to-customize-tick-marks-and-labels

Best_Days_To_Get_Into_Accident <- accident %>% ggplot(aes(x = DAY_WEEK))+
  geom_histogram(bins = 7, binwidth = .5)+ scale_x_continuous(breaks = seq(1, 7), labels = c("Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"))+
  ggtitle("Popular Days Accidents Occur")+ xlab("Days of Week")+ ylab("Number of Accidents")

Best_Times_To_Get_Into_Accident <- accident %>% filter(HOUR <= 24) %>% ggplot(aes(x = HOUR))+
  geom_histogram(bins = 24, binwidth = .5)+ scale_x_continuous(breaks = seq(0, 23), labels = c("12am", "1am", "2am", "3am", "4am", "5am", "6am", "7am", "8am", "9am", "10am", "11am", "12pm", "1pm", "2pm", "3pm", "4pm", "5pm", "6pm", "7pm", "8pm", "9pm", "10pm", "11pm"))+ theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+
  ggtitle("Popular Hours Accidents Occur throught a Day")+ xlab("Hour of Day")+ ylab("Number of Accidents")

grid.arrange(Best_Days_To_Get_Into_Accident, Best_Times_To_Get_Into_Accident, nrow = 2)

```


```{r}

accident %>% select(DRUNK_DR) %>% filter(DRUNK_DR >= 1) %>% summarize(n())

```

```{r}

driver_1 <- person %>% subset(PER_TYP == 1)

Joined_Data_ACCIDENTdrivers <- inner_join(driver_1, accident)

Tally_NumberOfAccidents <- Joined_Data_ACCIDENTdrivers %>% group_by(DAY_WEEK) %>% summarize(number = n())
Tally_NumberOfAccidents

Tally_HourOfDay <- Joined_Data_ACCIDENTdrivers %>% group_by(HOUR) %>% filter(HOUR <= 24) %>% summarize(number = n())
Tally_HourOfDay


#SEX is an interesting variable. Male(1) and Female(2). Looking at the FARS Analytical Report we see there are drivers with unidentified SEX: Not Reported(8) or Unknown(9)
Tally_Sex_MF <- Joined_Data_ACCIDENTdrivers %>% group_by(SEX) %>% filter(SEX == 1 | SEX == 2) %>% summarize(number = n())
Tally_Sex_MF

Tally_Sex_NotReported <- Joined_Data_ACCIDENTdrivers %>% group_by(SEX) %>% filter(SEX == 8) %>% summarize(number = n())
Tally_Sex_NotReported

Tally_Sex_Unkown <- Joined_Data_ACCIDENTdrivers %>% group_by(SEX) %>% filter(SEX == 9) %>% summarize(number = n())
Tally_Sex_Unkown

```


```{r}

Tally_NumberOfAccidents %>% ggplot(aes(x = DAY_WEEK, y = number ))+ geom_bar(stat = "identity") + geom_text(aes(label = c("Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"), vjust = -.2))+ theme(axis.text.x = element_blank(), axis.text.y = element_text(face = "bold", color = "black"))+
  ggtitle("Tally - number of accidents by day ")+ xlab("Days of Week")+ ylab("Number of Accidents")

```


```{r}

Tally_HourOfDay %>% ggplot(aes(x = HOUR, y = number ))+ geom_bar(stat = "identity")+
  geom_text(aes(label = c("12am", "1am", "2am", "3am", "4am", "5am", "6am", "7am", "8am", "9am", "10am", "11am", "12pm", "1pm", "2pm", "3pm", "4pm", "5pm", "6pm", "7pm", "8pm", "9pm", "10pm", "11pm"), angle = 90), hjust = 2 )+
   ggtitle("Tally - number of accidents by hour in a Day ")+ xlab("Hour of a Day")+ ylab("Number of Accidents")

```


```{r}
Tally_Sex_MF %>% ggplot(aes(x = SEX, y = number))+ geom_bar(stat = "identity")+
  geom_text(aes(label = c("Male", "Female"), vjust = 3.7), size = 6)+
  ggtitle("Tally - Male and Female ")+ xlab("Sex Identified")+ ylab("Number of Accidents")
  

```


```{r}

FRPP_GLC <- readxl::read_xlsx("FRPP GLC United States.xlsx")

colnames(FRPP_GLC) <- FRPP_GLC[1,]
FRPP_GLC <- FRPP_GLC[-1,]

county <- map_data('county')

FRPP_GLC_rename <- FRPP_GLC %>% mutate(STATE = as.integer(`State Code`), COUNTY = as.integer(`County Code`))#

Map_Join <- full_join(accident, FRPP_GLC_rename) %>% select("STATE", "COUNTY", "County Name", "State Name", "ST_CASE") %>% mutate(region = tolower(`State Name`), subregion = tolower(`County Name`)) %>% select("STATE", "COUNTY", "region", "subregion") %>% group_by(region, subregion) %>% summarize(number = n())

Map_Join_df <- full_join(county, Map_Join, by = c("region", "subregion"))


Map_Join_df %>% ggplot(aes(x = long, y = lat, fill = number))+ geom_polygon(aes(group = group))

```





```{r}


FRPP_GLC_TERR <- readxl::read_xlsx("FRPP GLC US Territories.xlsx")
colnames(FRPP_GLC_TERR) <- FRPP_GLC_TERR[1,]
FRPP_GLC_TERR[-1,]


```


```{r}
#library(lubridate)
#accident_weather <- accident %>% mutate(MONTH = as.Date(MONTH, origin = "1"))




```

